import type { Metadata } from "next";
import { Geist, Geist_Mono } from "next/font/google";
import '../globals.css';
import Sidebar from "../components/Sidebar";
import PageWrapper from "../components/PageWrapper";
import { AuthProvider } from "../AuthProvider";
import ServerNavbar from "../components/ServerNavbar";

const geistSans = Geist({
  variable: "--font-geist-sans",
  subsets: ["latin"],
});

const geistMono = Geist_Mono({
  variable: "--font-geist-mono",
  subsets: ["latin"],
});

export const metadata: Metadata = {
  title: "Create Next App",
  description: "Generated by create next app",
};

export default function RootLayout({
  children,
}: Readonly<{
  children: React.ReactNode;
}>) {
  return (
    <AuthProvider>
    <html lang="en">
      <body
        className={`${geistSans.variable} ${geistMono.variable} antialiased h-screen flex overflow-hidden`}
      >
     <div className="w-[14%]  md:w-[8%] lg:w-[16%] xl:w-[14%] ">
<Sidebar/>
        </div>
        <div className="flex flex-col h-full w-full">
              <ServerNavbar />
              <PageWrapper>
             {children}</PageWrapper>
            </div>
           </body>
    </html></AuthProvider>
  );
}
